### ISSUE TITLE
Where can i get apks or i HAVE TO build it on my own?

### ISSUE THREAD

**Issue by LEAFERx** [chrysler5798/RainbowSixAssistant#11]
I only find 1.8.4 now without the new season white noise updated.
Could you please build the apks and release them in the release tag?
I'm really a noob in android so it'd take a huge time for me to set the env and figure out how to build it.
So hope you could do it.
BTW, I really like this app XD.

**Comment by GpointChen** [comment]
I think that the apk on Play Store is the latest version, isn't it?

**Comment by LEAFERx** [comment]
sorry but in china, it's really not easy to access Play Store since it's google XD

**Comment by chrysler5798** [comment]
Hi, I built an APK for you, this is a in-development version tho, there should be no issue but still if you have anything don't hesitate to tell me. So you will officialy be the first user of the 1.9.4 😄 

Here it is :
https://www.dropbox.com/s/sy2ixpje7m6zny8/r6assistant-1-9-4.apk?dl=1

Thank you !

**Comment by LEAFERx** [comment]
@chrysler5798 
wow that's a great pleasure!
but.......i'm really sorry to say that dropbox is also blocked by china's GFW........
so......not work either.
why don't u try the github release feature?
https://github.com/blog/1547-release-your-software
thx very much again

**Comment by GpointChen** [comment]
I just upload the apk file to the Baidu Yun for you and it is only available in 7 days.

1.9.4: [Here](https://pan.baidu.com/s/1eS72tfO) with password "qp8z"
1.9.3 (official version on Play): [Here](https://pan.baidu.com/s/1eSOxnJ8) with password "84qv"

**Comment by LEAFERx** [comment]
@GpointChen thx bro!!!!
but it'd be better if there will be a official way that everyone(chinese player XD) could achieve the latest version without always making an issue, i think.

**Comment by GpointChen** [comment]
@LEAFERx yeah I also think so, therefore it is just the temporary solution for u. :D

**Comment by chrysler5798** [comment]
Thanks a lot @GpointChen 👍 
Sorry, didn't know China blocks Dropbox.
Yep, I will use release feature of Github for the next update. Thanks for the advice @LEAFERx 😃

**Comment by LEAFERx** [comment]
ur welcome
that app reeeeeally helps a lot
