### ISSUE TITLE
Same speed and number of gadgets

### ISSUE THREAD

**Issue by Khopylium** [chrysler5798/RainbowSixAssistant#9]
When you select operators per countries, all the caracters have the same speed (2/3) and the same armour (2/3)
A lot of gadgets are unbreakable like the Montagne's shield, but it's written it can be used 5 times only. Same problem for Rook; it's written he has 3 armours; This problem appears a lot of times, for a lot of characters.
Have a good day and good bye, Khopylium

**Comment by chrysler5798** [comment]
I fixed the speed and armor issue.

I will fix gadgets numbers tomorrow ! Thanks for your help 😃

**Comment by chrysler5798** [comment]
I fixed the number of unique gadgets.
I basically added JSON for speed armor and number of unique gadgets but the way to pick the JSON Object wasn't correct and it was picking a wrong one. I will work to add JSON resources without bug, for the moment I just took back the old method to just fix the bug.

Thanks for your feedback and have a good game 👍
